### ISSUE TITLE
Create export feature to sequence browser module

### ISSUE THREAD

**Issue by lassoan** [SlicerRt/Sequences#13]
Allow saving of all browsed nodes into a combined file, such as a sequence of image and multiple sequences of transforms to a single sequence metafile.

**Comment by matthewsholden** [comment]
In Perk Tutor, we implemented a way of exporting a sequence browser node as a single file that could be made generic to work with any sequence browser.

Essentially, to export, what it does is copies the sequence browser node, sequence nodes, and proxy nodes to a temporary scene. Then the temporary scene is saved as a zip file. To reload, the temporary scene is read from zip file, and the relevant sequence browser node, sequence nodes, and proxy nodes are copied into Slicer's main scene.

Here is the code https://github.com/PerkTutor/PerkTutor/blob/master/TransformRecorder/qSlicerTrackedSequenceBrowserWriter.cxx#L265-L367 (for writing) and https://github.com/PerkTutor/PerkTutor/blob/master/TransformRecorder/qSlicerTrackedSequenceBrowserReader.cxx#L280-L385 (for reading).

Do you think this is a good solution for exporting an arbitrary sequence browser? We could also implement specific exporters for particular types of sequences (e.g. tracked ultrasound sequences).

@lassoan

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
