### ISSUE TITLE
Add sequence recording

### ISSUE THREAD

**Issue by lassoan** [SlicerRt/Sequences#15]
- Allow mapping between any new/existing sequence and any new/existing data node
- Allow enable/disable saving and replaying for each mapped data-sequence node
- During recording: add a new item to the sequence whenever a data node changes; up to a maximum update rate
- Timestamp: starting time would be the timestamp of the last item of the master sequence node (time, s - whatever is used in sequence metafile)

**Comment by lassoan** [comment]
Integrated sequence recording feature developed by @mholden8 .

Code review comments:
- MetafileImporter\Logic\vtkSlicerMetafileImporterLogic.cxx - Use new vtkMathAddonUitlities in UpdateStringFromTransformNode and UpdateTransformNodeFromString
- vtkMRMLSequenceBrowserNode::vtkMRMLSequenceBrowserNode() 
- Why this->RecordingEvents->InsertNextValue( vtkCommand::ModifiedEvent ) is commented out?
- In vtkMRMLSequenceBrowserNode::AddVirtualOutputNodes it's not very nice that AddNodeReferenceRole is added for each reference (maybe needed for make things work when a scene is reloaded?)
- Consolidate vtkMRMLSequenceBrowserNode::SequenceNodeSynchronizationTypeOn and vtkMRMLSequenceBrowserNode::SequenceNodeSynchronizationTypeOff. Make on/off a boolean parameter.
- vtkMRMLSequenceBrowserNode::vtkMRMLSequenceBrowserNode()
  // TODO: Is this list of events complete. Is there a less arbitrary way to come up with the list of events
  // vtkCommand::AnyEvent grabs all of the events, but is very slow
  //this->RecordingEvents->InsertNextValue( vtkCommand::ModifiedEvent );
  this->RecordingEvents->InsertNextValue( vtkMRMLTransformableNode::TransformModifiedEvent );
  this->RecordingEvents->InsertNextValue( vtkMRMLVolumeNode::ImageDataModifiedEvent );
- vtkMRMLSequenceNode::SetDataNodeAtValue avoid special case copying of volumes

**Comment by matthewsholden** [comment]
@lassoan Thanks for the comments.

Could you please look at the branch https://github.com/mholden8/Sequences/tree/copy-node? It addresses the comments from @jcfr on the pull request #16. I think it also address some of the comments from your code review above. I'll update it to fully address your comments above.

**Comment by lassoan** [comment]
@mholden8 Could you please review the code review comments above and create separate issues for those that have not been addressed yet and close this issue?

**Comment by matthewsholden** [comment]
Created separate issue for maximum update rate: #21.

All other comments from the code review have already been addressed.
