### ISSUE TITLE
Save a loaded scene cuases Slicer crash

### ISSUE THREAD

**Issue by ungi** [SlicerRt/Sequences#23]
Tested with today's nightly: Slicer-4.7.0-2016-12-21-win-amd64.exe
To reproduce:

- Start Slicer
- Go to Sequence Browswer
- Add any Sequence
- Save the scene
- Restart Slicer
- Load the saved scene
- Try to save the scene again
- At this point Slicer crashes

These are the error messages from Slicer log:
[ERROR][VTK] 22.12.2016 15:21:35 [vtkMRMLSequenceNode (00000047FF5D5790)] (C:\D\N\E-0\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:452) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 22.12.2016 15:21:35 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 22.12.2016 15:21:35 [vtkMRMLSequenceNode (00000047FF5D5790)] (C:\D\N\E-0\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:452) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 22.12.2016 15:21:35 [] (unknown:0) - Item  0  has no index value defined

**Comment by lassoan** [comment]
Thanks for reporting this. Fixed in Slicer core  r25622.
