### ISSUE TITLE
Cannot load saved volume sequence as volume

### ISSUE THREAD

**Issue by matthewsholden** [SlicerRt/Sequences#31]
I would like to reload a saved ultrasound sequence in *.seq.nrrd format as a scalar volume in Slicer. The ultrasound image is 820 x 616 and there are 648 frames.

But, when I try to reload it, instead of getting a scalar volume of size 820 x 616 x 648, I get a vector volume of size 820 x 616 x 1 with 648 components. Please see the relevant part of the Slicer log below.

Note that if I try to reload a saved ultrasound sequence in *.mhd format, everything works as expected.

Any suggestions on how to do this?

```
[INFO][VTK] 11.08.2017 11:37:35 [vtkMRMLVolumeArchetypeStorageNode (00000217BCBFF240)] (C:\D\N\Slicer-0\Libs\MRML\Core\vtkMRMLVolumeArchetypeStorageNode.cxx:465) - Loaded volume from file: C:/Users/mholden8/Documents/Scratch/Subject20_H02-20170531-113907/Subject20_H02-20170531-113907/Data/Ultrasound_Ultrasoun-Sequence.seq.nrrd. Dimensions: 820x616x1. Number of components: 648. Pixel type: unsigned char.
[DEBUG][Qt] 11.08.2017 11:37:35 [] (unknown:0) - "Volume" Reader has successfully read the file "C:/Users/mholden8/Documents/Scratch/Subject20_H02-20170531-113907/Subject20_H02-20170531-113907/Data/Ultrasound_Ultrasoun-Sequence.seq.nrrd" "[1.78s]"
```

**Comment by lassoan** [comment]
Can you copy-paste here the first 20-30 lines of the nrrd header? Slicer's NRRD reader may expect 3D+t single-slice 3D volumes and Plus might save it as 2D+t.

**Comment by matthewsholden** [comment]
Here are the *.seq.nrrd file's header lines.

I'm happy to share the entire file. It is 73 MB. Please let me know how to send it.

I saved the ultrasound sequence from Slicer as a "Volume Sequence" using the Sequences extension. I did not save it from PLUS.

```
NRRD0005
# Complete NRRD file format specification at:
# http://teem.sourceforge.net/nrrd/format.html
type: unsigned char
dimension: 4
space: right-anterior-superior
sizes: 648 820 616 1
space directions: none (1,0,0) (0,1,0) (0,0,1)
kinds: list domain domain domain
labels: "time" "" "" ""
units: "s" "" "" ""
encoding: gzip
space origin: (0,0,0)
measurement frame: (1,0,0) (0,1,0) (0,0,1)
axis 0 index type:=numeric
axis 0 index values:=292.508 292.639 292.777 292.9 293.015 293.242 293.364 293.492 293.603 etc...
```

**Comment by lassoan** [comment]
The header looks good.

Did you drag-and-drop the .seq.nrrd file to Slicer? Did it offer to load it as "Volume sequence"?

**Comment by matthewsholden** [comment]
Yes, I drag and drop the *.seq.nrrd file into Slicer. It offers to load it as a "Volume Sequence" and that works well. But when I try to load as a "Volume" I encounter the above issue.

**Comment by lassoan** [comment]
This is the expected behavior. For example, you may want load a 3-component volume as an RGB volume, as a sequence of 3 volumes, or as a displacement field - all valid interpretations. If you load the file programmatically, then set "Volume sequence" as file type if you want to interpret the file as a volume sequence.

It would be great if you could recommend how/where to improve documentation to describe the behavior more clearly.

**Comment by matthewsholden** [comment]
I see. I suppose what was confusing me is that when I saved the ultrasound image sequence as *.mhd, when I reload as a "Volume", I get a 820 x 616 x 648 scalar volume. But when I saved the ultrasound image sequence as *.seq.nrrd, when I reload as a "Volume", I get a 820 x 616 x 1 vector volume with 648 components.

But I see the utility in this behaviour when saving a sequence of 3D volumes into *.seq.nrrd format.

**Comment by lassoan** [comment]
> when I saved the ultrasound image sequence as *.mhd

Probably we should save as .seq.mhd to load the file as a sequence by default. What was your workflow? Where the .mhd file came from?

Do we need to change something in documentation or software implementation?

**Comment by matthewsholden** [comment]
Through the Python interactor, it is possible to save a Sequence Browser node containing one 2D volume sequence and an arbitrary number of transform sequences into an *.mhd file. I used this to save sequences of tracked ultrasound images into a single file. The *.mhd file is in the same format as the *.mhd files written by PLUS. But saving to *.mhd was never available through the widget or save dialogs. Note that *.seq.mhd files are already loaded as Sequences by default.

Frankly, I don't really care about the *.mhd file. I just wanted to contrast how it is loaded against how the *.seq.nrrd file is loaded. But I now understand why the *.seq.nrrd file is loaded the way it is.

I suppose adding something into the documentation about how Sequences may be saved and the different formats it could be saved into. Shall I add it here https://www.slicer.org/wiki/Documentation/Nightly/Extensions/Sequences?

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
