### ISSUE TITLE
Slicer crashes when proxy node is deleted

### ISSUE THREAD

**Issue by moselhy** [SlicerRt/Sequences#32]
To reproduce this issue, do the following:

1. Start Slicer
2. Import CTP-cardio sequence from Sample Data module
3. Create new SequenceBrowser
4. Add CTP-cardio sequence to the new browser and allow renaming of proxy node
5. Delete the old CTP-cardio browser
6. Delete the old browser's proxy node

Suggested fix:
When browser nodes are deleted, delete their associated proxy nodes

**Comment by lassoan** [comment]
Thanks for reporting this, we'll fix this soon.

**Comment by matthewsholden** [comment]
I no longer get a crash when I follow these steps using the latest Slicer nightly.

@moselhy Could you please confirm whether this solves the issues you were encountering?

**Comment by moselhy** [comment]
> I no longer get a crash when I follow these steps using the latest Slicer nightly.

Me neither, this is now solved.
