### ISSUE TITLE
Transform sequences read as identities

### ISSUE THREAD

**Issue by matthewsholden** [SlicerRt/Sequences#35]
When reloading a transform sequences from an *.mha or *.mhd file format, the resulting imported sequence contains a sequence of identity transforms. 

This issue also seems to affect importing entire sequence metafiles.

**Comment by lassoan** [comment]
This sounds like a significant regression. It may be related to my recent changes:
https://github.com/SlicerRt/Sequences/commit/c89dd0825f3e511ae2efffae6ae252eb0dd4af6b

@mholden8 Do you have time to investigate?

We should also add a basic test for metafile reading to prevent such regressions in the future.

**Comment by matthewsholden** [comment]
Yes, I will look into it.

**Comment by matthewsholden** [comment]
@lassoan, could you please send a dataset that was failing prior to https://github.com/SlicerRt/Sequences/commit/c89dd0825f3e511ae2efffae6ae252eb0dd4af6b? I would like to make sure the changes I make don't introduce a regression causing this to fail again.

**Comment by lassoan** [comment]
https://github.com/moselhy/SlicerSequenceRegistration extension failed to save grid transforms before the change. You can follow the tutorial steps described on the extension's webpage to see if things work well (computed output transform sequence contain valid, non-identity matrices) or create a pull request and I'll test it.

**Comment by matthewsholden** [comment]
Thanks for the quick fix, @lassoan. It is working for me now.
