### ISSUE TITLE
Add/remove sequence refresh problem

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/Sequences#42]
It seems that when adding or removing a sequence, the UI in SequenceBrowser does not refresh until the button is pressed again, or the sequence node is changed to another than back.

Example: I click add sequence once, nothing seems to happen. Click it another time, new row added in the table. But if I choose another node and back, then there will be two sequences.

Note that I noticed it during an experiment and quickly added an issue, but this needs to be confirmed.

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
