### ISSUE TITLE
Sequence files with no transforms aren't loaded and no error is reported

### ISSUE THREAD

**Issue by adamrankin** [SlicerRt/Sequences#45]
After debugging, it is due to 
```c++
  if (vtkMRMLLinearTransformSequenceStorageNode::ReadSequenceMetafileTransforms(fileName, this->GetMRMLScene(),
    createdSequenceNodes,
    frameNumberToIndexValueMap, imageMetaData) == 0)
  {
    // error is logged in ReadTransforms
    return NULL;
  }
```

The return null should not happen, and the code should continue without issue.

The function returns the number of nodes created, but perhaps should take the number of nodes created as a reference argument and return an error code instead. That way 0 nodes and no error is more informative than just 0 nodes created, reason unknown.

**Comment by lassoan** [comment]
I agree that it should be possible to read a sequence metafile, even when transforms are not specified. We should probably just log a warning. I think this should already work with image sequence in nrrd format.

**Comment by adamrankin** [comment]
Fixed.
