### ISSUE TITLE
BUG: vtkNRRDReader / Writer do not exist in modern VTK

### ISSUE THREAD

**Issue by phcerdan** [SlicerRt/Sequences#48]
They were renamed to vtkNrrdReader vtkNrrdWriter. Hitting this building the module with VTKv9

**Comment by jcfr** [comment]
If you are building a Custom slicer app, this happens because the version numbers are improperly managed. A fix is on the way.

**Comment by phcerdan** [comment]
Indeed I am, such a good thing that you know what I am doing, thanks @jcfr!

**Comment by jcfr** [comment]
>  improperly managed

To clarify, the issue is in Slicer + SlicerCustomAppTemplate, this is not specific to your current project. 

We faced the problem at the project week here in Canada ..

**Comment by phcerdan** [comment]
Yeah, I guessed so. I am testing your PR in SlicerSALT, which I guess uses the SlicerCustomAppTemplate.

**Comment by jcfr** [comment]
The PR in SlicerSALT was generated using [SlicerCustomAppTemplate](https://github.com/KitwareMedical/SlicerCustomAppTemplate), we will have to sync when the template will be updated

**Comment by phcerdan** [comment]
Thanks @jcfr for solving it upstream, [here in SlicerCustomAppTemplate](https://github.com/KitwareMedical/SlicerCustomAppTemplate/commit/366652a28580f1a3400d5b3447d91ebfbf831d1f), and [here in Slicer](https://github.com/Slicer/Slicer/commit/8af26f65267f2b316eeee78035c22f835d485abf)
