### ISSUE TITLE
igs versus seq

### ISSUE THREAD

**Issue by jamesobutler** [SlicerRt/Sequences#61]
I acquire sequences with tracked frames.  Should I be using the igs extension prefix or the seq extension prefix?

I saw in a discussion when igs was introduced that @lassoan said it should be for tracked frames. I don't see anywhere that igs is being handled differently from seq files. Is there a plan for this in the future? Or is this igs versus seq difference strictly an indicator to know if there are tracked frames in the file without having to open it?

**Comment by lassoan** [comment]
.igs.nrrd and .igs.mha are new composite file extensions for sequence files. They allow Slicer (and users) to see that the file contains tracked image data, without looking into the file. We'll update Plus to use these composite file extensions by default (https://github.com/PlusToolkit/PlusLib/issues/437).

**Comment by jamesobutler** [comment]
Ok thanks for the information. So if Plus capture with tracked data is recorded and saved as say .igs.mhd and then that is passed through Plus's Volume Reconstructor, should the output not have composite file extension since it is no longer a sequence, but a static volume? So use .mha or .mhd.

**Comment by lassoan** [comment]
Yes, reconstructed volumes are just plain 3D volumes with mha/mhd/nrrd/nhdr extension (without igs prefix).
