### ISSUE TITLE
Viewing sequences without transforms problems

### ISSUE THREAD

**Issue by jamesobutler** [SlicerRt/Sequences#64]
I was using Plus to record a webcam stream(no tracker devices present so no transforms) and then trying to playback the saved sequence with Slicer Sequences, but loading it as Sequence Metafile wasn't showing the individual frames correctly.  It was as though multiple frames at once were being displayed at once and then played. DimSize in the header is showing as "3 640 480 58". When the sequence is loaded as a volume it is shown as a 3x3 grid of frames.

**Comment by lassoan** [comment]
@Sunderlandkyl could you have a look at this?

**Comment by Sunderlandkyl** [comment]
Looks like the problem is in Plus (now IGSIO).
```
DimSize = 3 640 480                  147
```

Should be:
```
DimSize = 640 480 147
```

**Comment by jamesobutler** [comment]
Let me know if you want me to create a git issue in another repo with corresponding details.

**Comment by Sunderlandkyl** [comment]
So, for now, Metafile sequences saved in Plus are considered to be incompatible with Slicer.

Once the SlicerIGSIO extension has been updated to the latest IGSIO branch, we can add support for sequence Metafile IO by accessing the same classes that Plus currently uses.

**Comment by Sunderlandkyl** [comment]
I should also mention that NRRD is supposed to still be supported.

I had issues with loading NRRD sequence files from Plus when I tested it earlier today, but I'll continue looking into that tomorrow.

**Comment by jamesobutler** [comment]
Yes, it does appear to be an issue with NRRD as well. I just attempted to load an .igs.nrrd sequence as Sequence Metafile with Slicer 4.10.0 and the loading progress bar got stuck. 
The Slicer log last reported:

> [WARNING][VTK] 12.12.2018 22:23:59 [vtkSlicerMetafileImporterLogic (000000000E5B0650)] (D:\D\S\S-4100-E-b\Sequences\MetafileImporter\Logic\vtkSlicerMetafileImporterLogic.cxx:331) - No transforms read from metafile: C:/Users/jobutler/PlusApp-2.7.0.20181211-Win64/data/RecordingTest_20181212_222301.igs.nrrd

The nrrd header is showing `sizes: 3 640 480                     166` which is similar to what was observed with the metaimage capture DimSize.

I'm using the config file [PlusDeviceSet_Server_MmfColorVideoCapture.xml](https://github.com/PlusToolkit/PlusLibData/blob/47d20c24ced72c22f7957b80bfdee9ff5d4d5594/ConfigFiles/PlusDeviceSet_Server_MmfColorVideoCapture.xml) for testing and simply setting EnableCapturingOnStart to "TRUE" while testing with different primary extension types (nrrd/nhdr/mha/mhd).

**Comment by Sunderlandkyl** [comment]
Sorry, I'm coming back to this now.
The cause of the issue is that the images are in color. Greyscale images saved in Plus using mha (with or without transforms) can be loaded using Sequences.

I'm working on the issue with loading NRRD sequence files saved from Plus.

**Comment by jamesobutler** [comment]
Ok. Interesting how color images causes MHA sequences to not be loaded correctly...

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
