### ISSUE TITLE
Add option to set time format in sequence browser widget

### ISSUE THREAD

**Issue by ungi** [SlicerRt/Sequences#67]
Currently the sequence browser widget displays the timestamps as is. But often timestamps have variable number of decimal digits, and/or unnecessarily many decimal digits. This causes the slider to jump between different lengths (depending on how much space is left besides the timestamp text).
Could you please add an option to the browser widget to reformat the displayed timestamp? Since not all fonts have fixed width characters, it would also be nice to have an option that fixes the width of the slider widget.

**Comment by Sunderlandkyl** [comment]
#73 Improves value display (no variable number of decimals).
The number of characters in value display can still vary when changing the number of digits in the value's integer part. I will make another pull request to address that as well.

**Comment by ungi** [comment]
Thank you. If there is a chance to fix the width of the slider (and/or the label) somehow, that would be ideal. Because the digit 1 is narrower than most other digits in most font types.

**Comment by Sunderlandkyl** [comment]
I think that it already used the fixed width font, but I set it explicitly to make sure (https://github.com/SlicerRt/Sequences/pull/73/files#diff-36fab958d7936b745276f78bb7778242R59)
