### ISSUE TITLE
Switching from showing time to frame number

### ISSUE THREAD

**Issue by amashari** [SlicerRt/Sequences#71]
When opening a scene after a restart sequences browser shows frame count (e.g. 5/37). After closing a scene and opening another (no restart) it switches to displaying the frame time. Is it possible to toggle time/frame number display?

**Comment by matthewsholden** [comment]
In the Advanced tab of the Sequence Browser module, there is a setting called "Index display". Change this to "Index" to show the frame number.

You can also change this programmatically with:

```python
mySequenceBrowserNode.SetIndexDisplayMode(slicer.vtkMRMLSequenceBrowserNode.IndexDisplayAsIndex)
``` 

Note that this is a property of the sequence browser node, not a universal setting in the Sequence Browser module. Probably the sequence browser nodes in your two scenes have different index display properties.

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
