### ISSUE TITLE
Error message when trying to save image sequence

### ISSUE THREAD

**Issue by ungi** [SlicerRt/Sequences#75]
When trying to save a Slicer scene with a webcam compressed video sequence (and a position tracking sequence), I get this error message:
(Plus config file attached.) I'm using nightly PLUS and Slicer.
Also, the webcam video sequence is not saved in the Slicer scene.
[HerniaTutor.txt](https://github.com/SlicerRt/Sequences/files/3249102/HerniaTutor.txt)

[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Session start time .......: 2019-06-03 15:08:09
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Slicer version ...........: 4.11.0-2019-05-31 (revision 28283) win-amd64 - installed release
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Operating system .........: Windows /  Professional /  (Build 9200) - 64-bit
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Memory ...................: 32586 MB physical, 37450 MB virtual
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - CPU ......................: GenuineIntel , 12 cores, 12 logical processors
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Qt configuration .........: version 5.10.1, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Developer mode enabled ...: no
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 03.06.2019 15:08:09 [] (unknown:0) - Additional module paths ..: C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/SlicerOpenIGTLink/lib/Slicer-4.11/qt-loadable-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/SlicerOpenIGTLink/lib/Slicer-4.11/qt-scripted-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/SlicerIGT/lib/Slicer-4.11/qt-loadable-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/SlicerIGT/lib/Slicer-4.11/qt-scripted-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/SlicerIGSIO/lib/Slicer-4.11/qt-loadable-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/Sequences/lib/Slicer-4.11/qt-loadable-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/Sequences/lib/Slicer-4.11/qt-scripted-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/DebuggingTools/lib/Slicer-4.11/qt-scripted-modules, C:/Users/ungi/AppData/Roaming/NA-MIC/Extensions-28283/SlicerJupyter/lib/Slicer-4.11/qt-loadable-modules
[DEBUG][Python] 03.06.2019 15:08:11 [Python] (C:\Program Files\Slicer 4.11.0-2019-05-31\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 03.06.2019 15:08:12 [Python] (C:\Program Files\Slicer 4.11.0-2019-05-31\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 03.06.2019 15:08:12 [Python] (C:\Program Files\Slicer 4.11.0-2019-05-31\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 03.06.2019 15:08:12 [] (unknown:0) - Switch to module:  "Welcome"
[DEBUG][Qt] 03.06.2019 15:08:31 [] (unknown:0) - Switch to module:  "OpenIGTLinkIF"
[INFO][VTK] 03.06.2019 15:08:34 [vtkMRMLIGTLConnectorNode (0000020CC47CEBF0)] (D:\D\P\S-0-E-b\SlicerOpenIGTLink\OpenIGTLinkIF\MRML\vtkMRMLIGTLConnectorNode.cxx:1114) - Connected: localhost:18944
[DEBUG][Qt] 03.06.2019 15:08:52 [] (unknown:0) - Switch to module:  "CreateModels"
[DEBUG][Qt] 03.06.2019 15:08:54 [] (unknown:0) - Switch to module:  "Data"
[DEBUG][Qt] 03.06.2019 15:09:11 [] (unknown:0) - Switch to module:  "SequenceBrowser"
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:13 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:13 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:22 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:22 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:22 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:22 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:24 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:24 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:24 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:24 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:27 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:27 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:27 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:27 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:33 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:33 [] (unknown:0) - Item  0  has no index value defined
[ERROR][VTK] 03.06.2019 15:09:33 [vtkMRMLSequenceNode (0000020CC497E8A0)] (D:\D\P\S-0-E-b\Sequences\Sequences\MRML\vtkMRMLSequenceNode.cxx:529) - vtkMRMLSequenceNode::GetNthIndexValue failed, invalid seqItemIndex value: 0
[WARNING][Qt] 03.06.2019 15:09:33 [] (unknown:0) - Item  0  has no index value defined
[DEBUG][Qt] 03.06.2019 15:12:41 [] (unknown:0) - Switch to module:  "Sequences"
[WARNING][Qt] 03.06.2019 15:12:41 [] (unknown:0) - QObject::connect: No such slot qSlicerSequencesModuleWidget::onHideDataNodeClicked( int, int )
[WARNING][Qt] 03.06.2019 15:12:41 [] (unknown:0) - QObject::connect:  (sender name:   'TableWidget_DataNodes')
[WARNING][Qt] 03.06.2019 15:12:41 [] (unknown:0) - QObject::connect:  (receiver name: 'SequencesModuleWidget')

**Comment by Sunderlandkyl** [comment]
Streaming compressed video needs to use the "VIDEO" message type. See: https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_CompressedVideo.xml

**Comment by Sunderlandkyl** [comment]
@ungi I'm going to re-open this to investigate the problem as an issue with saving regular (non-compressed) volume sequences.

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
