### ISSUE TITLE
Set Transform for Sequences data

### ISSUE THREAD

**Issue by guangxv** [SlicerRt/Sequences#86]
How to set a transform for sequence node using python script?
It is convenience using 'SetAndObserveTransformNodeID()' to set transform for volume node. However, it does not valid for sequence node.
Must I use 'GetNthDataNode()' function to set the transformation for each DataNode?
Thank you very much.

**Comment by ungi** [comment]
In practice, you would only use the proxy node of a sequence node. If you use SetAndObserveTransformNodeID() on the proxy node, then as you browse through the sequence using a sequence browser node, the proxy node would always stay transformed.

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
